// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sampler
Rcpp::List sampler(arma::uvec Y_sorted, arma::uvec Y_failure, arma::mat X, double lambda, double kernel_sd, arma::uword mcmc_samples, bool verbose);
RcppExport SEXP _survival_ss_sampler(SEXP Y_sortedSEXP, SEXP Y_failureSEXP, SEXP XSEXP, SEXP lambdaSEXP, SEXP kernel_sdSEXP, SEXP mcmc_samplesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type Y_sorted(Y_sortedSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Y_failure(Y_failureSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type kernel_sd(kernel_sdSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type mcmc_samples(mcmc_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sampler(Y_sorted, Y_failure, X, lambda, kernel_sd, mcmc_samples, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_survival_ss_sampler", (DL_FUNC) &_survival_ss_sampler, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_survival_ss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
