# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampler <- function(Y_sorted, Y_failure, X, lambda, kernel_sd, mcmc_samples, verbose) {
    .Call(`_survival_ss_sampler`, Y_sorted, Y_failure, X, lambda, kernel_sd, mcmc_samples, verbose)
}

